# Generated by Django 5.0.6 on 2024-09-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('drug_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drug.drug')),
            ],
        ),
    ]
